services:
  staging-area:
    container_name: staging-area
    build:
      dockerfile: ./docker/staging-area/Dockerfile
    ports:
      - "3306:3306"
  data-warehouse:
    container_name: data-warehouse
    build:
      dockerfile: ./docker/data-warehouse/Dockerfile
    ports:
      - "3307:3306"
  northwind:
    container_name: northwind
    build:
      dockerfile: ./docker/northwind/Dockerfile
    ports:
      - "1433:1433"
  mappings:
    container_name: mappings
    build:
      dockerfile: ./docker/mappings/Dockerfile
    ports:
      - "3308:3306"
