services:
  staging-area:
    container_name: staging-area
    build:
      dockerfile: ./docker/staging-area/Dockerfile
    ports:
      - "3306:3306"
  data-warehouse:
    container_name: data-warehouse
    build:
      dockerfile: ./docker/data-warehouse/Dockerfile
    ports:
      - "5433:5433"
  northwind:
    container_name: northwind
    build:
      dockerfile: ./docker/northwind/Dockerfile
    ports:
      - "1433:1433"
